### ISSUE TITLE
add clang flags using clang-ctags?

### ISSUE THREAD

**Issue by hongxuchen** [drothlis/clang-ctags#1]
When I use `clang-ctags` to analyze c/c++ source files, there is always an error telling me that **'stddef.h' file not found**, I suppose that I need to pass a flag `-I` telling that it should include the header file location, however I don't know how to add the option in the command line according to `README` or  `clang-ctags --help`

**Comment by drothlis** [comment]
> 'stddef.h' file not found

This sounds like #5, which was fixed in #7.
