### ISSUE TITLE
Clang failed to parse '-print-search-dirs'

### ISSUE THREAD

**Issue by vmiheer** [drothlis/clang-ctags#2]
I exported CC and CXX to shell script with:
# !/bin/sh

clang-ctags -f tagfile --append -- "$@"
g++ "$@"

**while configuring I get following error:**
checking dynamic linker characteristics... clang-ctags: Error: Clang failed to parse '-print-search-dirs'
Exception ctypes.ArgumentError: "argument 1: <type 'exceptions.AttributeError'>: 'TranslationUnit' object has no attribute '_as_parameter_'" in <bound method TranslationUnit.__del__ of <clang.cindex.TranslationUnit object at 0x29b8290>> ignored

**And while compiling**
clang-ctags: Error: File '/home/miheer/Videos/llvm/lib/Support/APFloat.cpp' failed clang's parsing and type-checking

**Comment by drothlis** [comment]
Closing issues with no response from reporter in 1 year.
