### ISSUE TITLE
clang-ctags crashes (Core dumped)

### ISSUE THREAD

**Issue by RedX2501** [drothlis/clang-ctags#4]
I have created a compile_database. When invoking the python script it crashes.

My command-line is:

```
~/clang-ctags/clang-ctags --compile-commands . -v (...the file...)
Processing file 1 of 1: (...the file ...)
Aborted (core dumped)
```

Any ideas on how i could proceed to debug this?

```
clang version 3.4.2 (tags/RELEASE_34/dot2-final)
```

I'm working on cygwin

**Comment by drothlis** [comment]
Closing issues with no response from reporter in 1 year.
