### ISSUE TITLE
Files can be compile but failed type-checking, then tag generating failed

### ISSUE THREAD

**Issue by 4pao** [drothlis/clang-ctags#6]
explicit instantiation of undefined function template 'Calculate'
explicit instantiation of undefined function template 'Calculate'
clang-ctags: Error: File '/Users/intel/Workspace/llvm/lib/IR/Dominators.cpp' failed clang's parsing and type-checking

I think there is no need to do type-checking when generating tags?

**Comment by drothlis** [comment]
Could you please provide a minimal test-case? Thanks!

**Comment by 4pao** [comment]
OK, Actually I have provide it, implicitly. I use clang-ctags to tag the whole llvm/clang code base. It will fail on several source code. You can fun this commands:

clang-ctags -v --extra-qualifier-tags --compile-commands=.build/compile_commands.json lib/IR/Dominators.cpp

After building compile database in directory ".build". It will fail with message:

explicit instantiation of undefined function template 'Calculate'
explicit instantiation of undefined function template 'Calculate'
clang-ctags: Error: File '/Users/intel/Workspace/llvm/lib/IR/Dominators.cpp' failed clang's parsing and type-checking

**Comment by 4pao** [comment]
I mean, we can disable the type-checking and just let clang do parse. That would be more fast and less error.

**Comment by drothlis** [comment]
> I use clang-ctags to tag the whole llvm/clang code base.

By "minimal test-case" I meant a small code sample that we could put in the clang-ctags test suite.

> we can disable the type-checking and just let clang do parse.

Is that even possible with C++? Do you know how to do that with Clang?

**Comment by drothlis** [comment]
Closing issues with no response from reporter in 1 year.
